config/routes.rb
MyappV1::Application.routes.draw do
  resources :users do
    member do
      get :password
      patch :change_password
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  root to: 'sessions#new'

  match '/signup', to: 'users#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/home', to: 'static_pages#home', via: 'get'
  

  

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :users
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	belongs_to :branch
	belongs_to :role

	validates_presence_of :ename, message: '英文名不能为空'
	validates_presence_of :cname, message: '中文名不能为空'
	validates_presence_of :email, message: '邮箱地址不能为空'
	validates_presence_of :branch_id, message: '所属分支机构不能为空'
	#validates_presence_of :role_id, message: '角色名不能为空'

	validates :ename, :length=>{ maximum: 10, too_long: '英文名不得超过10位' }
	validates :cname, :length=>{ maximum: 10, too_long: '中文名不能超过5位' }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, format: { with: VALID_EMAIL_REGEX, :message => '邮箱格式不正确' },
		uniqueness: { case_sensitive: false, :message => '您的邮箱已被注册' }

	validates_length_of :password, :within => 6..10, message: '密码长度错误，应在6到10位之间', allow_nil: true

	has_secure_password

	attr_reader :current_password
	def update_password(user_params)
		current_password = user_params.delete(:current_password)

		#旧密码
		unless self.authenticate(current_password)
			self.errors.add(:current_password, current_password.blank? ? '旧密码不能为空' : '旧密码不正确')
			return false
		end

		#新密码
		unless user_params[:password].present?
			self.errors.add(:password, '请输入新密码')
			return false
		end

		unless user_params[:password].length.between?(6,10)
			self.errors.add(:password, '新密码长度不正确，应该在6到10位之间')
			return false
		end

		self.update(user_params)
	end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	def admin?
		self.role.role_name == 'admin'
	end

	private
		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
	before_action :signed_in_user

	def new
		@branch = Branch.new
	end

	def create
		@branch = Branch.new
		@branch.save
	end

	private
		def signed_in_user
			redirect_to root_path, notice: "您还未登陆，请先登陆！" unless signed_in?
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	layout 'signup', only: :new
	before_action :signed_in_user, only: [:destroy]
	
	def new
		@new_email = params[:email].downcase unless params[:email].nil?
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_to home_path
		else
			flash.now[:error] = '邮箱地址/密码不正确。'
			render 'new', :layout => "signup"
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end

	private
		def signed_in_user
			redirect_to root_path, notice: "您还未登陆，请先登陆！" unless signed_in?
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :signed_in_user

	def home
	end

	private
	def signed_in_user
		redirect_to root_path, notice: "您还未登陆，请先登陆！" unless signed_in?
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	layout 'signup', only: :new
	before_action :signed_in_user, only: [:edit, :update, :show, :index]
	before_action :correct_user, only: [:edit, :update]
	before_action :admin_user, only: [:destroy]

	def index
		@users = User.all
		#@users = User.paginate(page: params[:page], per_page: 10)
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "恭喜您，注册成功，请重新登陆！"
			redirect_to root_path(email: @user.email), :layout => "signup"
		else
			render 'new', :layout => "signup"
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		_checked = params[:_checked] || '0'
		if _checked == '1'	
			if @user.update_attributes(user_params)
				flash[:success] = "更新成功!"
				sign_in @user
				redirect_to @user
			else
				render 'edit'
			end
		else
			if @user.update_attributes(user_params)
				flash[:success] = "更新成功!"
				sign_in @user
				redirect_to @user
			else
				render 'edit'
			end
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:success] = "用户【#{@user.cname}】，删除成功!"
		redirect_to users_path
	end

	def password
		@user = User.find(params[:id])
	end

	def change_password
		@user = User.find(params[:id])
		if  @user.update_password(user_params)
			flash[:success] = "密码修改成功！"
			redirect_to home_path
		else
			render 'password'
		end
	end

	private
		def user_params
			params.require(:user).permit(:ename, :cname, :email, 
							:branch_id, :role_id, :current_password,
							:password, :password_confirmation)
		end

		def signed_in_user
			unless signed_in?
				store_location
				redirect_to root_path, notice: "您还未登陆，请先登陆！"
			end
		end

		def correct_user
			@user = User.find(params[:id])
			redirect_to home_path, notice: "对不起，您不能查看他人的资料！" unless current_user?(@user)
		end

		def admin_user
			redirect_to home_path, notice: "对不起，只有管理员才能进行此操作！" unless current_user.admin?
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "My Web App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		#cookies[:remember_token] = { value: remember_token, expires: 15.minutes.from_now }
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_to(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.fullpath
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <div class='navbar'>
    <div class='navbar-inner'>
      <div class='container-fluid'>
      	<%= link_to root_path, class: 'brand' do %>
          <i class='icon-heart-empty'></i>
          <span class='hidden-phone'>My Web App</span>
        <% end %>
        <a href='#' class='toggle-nav btn pull-left'>
          <i class='icon-reorder'></i>
        </a>
        <% if signed_in? %>
          <ul class='nav pull-right'>
            <li class='dropdown medium only-icon widget'>
              <a href='#' class='dropdown-toggle' data-toggle='dropdown'>
                <i class='icon-rss'></i>
                <div class='label'>3</div>
              </a>
              <ul class='dropdown-menu'>
                <li>
                  <a href='#'>
                    <div class='widget-body'>
                      <div class='pull-left icon'>
                        <i class='icon-user text-success'></i>
                      </div>
                      <div class='pull-left text'>
                        John Doe signed up
                        <small class='muted'>just now</small>
                      </div>
                    </div>
                  </a>
                </li>
                <li class='divider'></li>
                <li>
                  <a href='#'>
                    <div class='widget-body'>
                      <div class='pull-left icon'>
                        <i class='icon-inbox text-error'></i>
                      </div>
                      <div class='pull-left text'>
                        New Order #002
                        <small class='muted'>3 minutes ago</small>
                      </div>
                    </div>
                  </a>
                </li>
                <li class='divider'></li>
                <li>
                  <a href='#'>
                    <div class='widget-body'>
                      <div class='pull-left icon'>
                        <i class='icon-comment text-warning'></i>
                      </div>
                      <div class='pull-left text'>
                        America Leannon commented Flatty with veeery long text.
                        <small class='muted'>1 hour ago</small>
                      </div>
                    </div>
                  </a>
                </li>
                <li class='widget-footer'>
                  <a href='#'>All notifications</a>
                </li>
              </ul>
            </li>
            <li class='dropdown dark user-menu'>
              <a class='dropdown-toggle' data-toggle='dropdown' href='#'>
                <%= image_tag "avatar.jpg", alt: current_user.cname, height: '23', width: '23' %>
                <span class='user-name hidden-phone'><%= @current_user.cname %></span>
                <b class='caret'></b>
              </a>
              <ul class='dropdown-menu'>
                <li>
                  <%= link_to current_user do %>
                    <i class='icon-user'></i>
                    个人资料
                  <% end %>
                </li>
                <li>
                  <%= link_to edit_user_path(current_user) do %>
                    <i class='icon-wrench'></i>
                    编辑
                  <% end %>
                </li>
                <li>
                  <%= link_to password_user_path(current_user) do %>
                    <i class='icon-cog'></i>
                    修改密码
                  <% end %>
                </li>
                <li class='divider'></li>
                <li>
                  <%= link_to signout_path, method: "delete" do %>
                    <i class='icon-signout'></i>
                    登出
                  <% end %>
                </li>
              </ul>
            </li>
          </ul>
        <% else %>
          <ul class='nav pull-right'>
            <li>
              <%=link_to root_path, class: 'user-name hidden-phone' do %>
                <i class='icon-arrow-right'></i>
                登录
              <% end %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_nav.html.erb
<nav class='' id='main-nav'>
  <div class='navigation'>
    <ul class='nav nav-stacked'>
      <li class='active'>
        <%= link_to home_path do %>
          <i class='icon-dashboard'></i>
          <span>主页</span>
        <% end %>
      </li>
      <li>
        <a class='dropdown-collapse' href='#'>
          <i class='icon-cogs'></i>
          <span>个人资料管理</span>
          <i class='icon-angle-down angle-down'></i>
        </a>
        <ul class='nav nav-stacked'>
          <li>
            <%= link_to current_user do %>
              <i class='icon-user'></i>
              <span>查看</span>
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_path(current_user) do %>
              <i class='icon-wrench'></i>
              <span>编辑</span>
            <% end %>
          </li>
          <li>
            <%= link_to password_user_path(current_user) do %>
              <i class='icon-cog'></i>
              <span>修改密码</span>
            <% end %>
          </li>
        </ul>
      </li>
      <li class='active'>
        <%= link_to users_path do %>
          <i class='icon-group'></i>
          <span>用户列表</span>
        <% end %>
      </li>
      <li class='active'>
        <%= link_to signout_path, method: "delete" do %>
          <i class='icon-signout'></i>
          <span>登出</span>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_shiv.html.erb
<!--[if lt IE 9]>
	<script src="assets/javascripts/html5shiv.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shiv' %>
</head>
<body class ='contrast-fb'>
	<%= render 'layouts/header' %>
	<div id='wrapper'>
		<div id='main-nav-bg'></div>
		<%= render 'layouts/nav' %>
    <section id='content'>
      <div class='container-fluid'>
        <div class='row-fluid' id='content-wrapper'>
          <div class='span12'>
        		<% flash.each do |key, value| %>
        			<%= content_tag(:div, value, class: "alert alert-#{key}" ) %>
        		<% end %>
        		<%= yield %>
        		<%= debug(params) if Rails.env.development? %>
          </div>
        </div>
      </div>
    </section>
	</div>
</body>
</html>

app/views/layouts/signup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shiv' %>
  </head>
  <body class='contrast-fb sign-up contrast-background'>
  	<div id='wrapper'>
    	<div class='application'>
      	<div class='application-content'>
        	<%= link_to '#' do %>
          	<div class='icon-heart'></div>
          	<span>My Web App</span>
        	<% end %>
      	</div>
    	</div>
      <%= yield %>
  	</div>
  	<%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			对不起，请检查下列 <%= object.errors.count %>个错误：
		</div>
		<ul>
		<% object.errors.messages.each do |msg| %>
			<li> * <%= msg.second.join('，') %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, '主页') %>
<div class='page-header'>
  <h1 class='pull-left'>
    <i class='icon-dashboard'></i>
    <span>占坑</span>
  </h1>
</div>
<div>
  <p>再次占坑</p>
</div>

app/views/users/_user.html.erb
<tr>
  <td><%= user.cname %></td>
  <td><%= user.email %></td>
  <td><%= user.branch.branch_name %></td>
  <td><%= user.role.role_cname %></td>
  <td><%= user.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
  <td>
    <div class='text-right'>
      <%= link_to user_path(user.id), class: 'btn btn-info btn-mini has-tooltip', :'data-placement'=> 'bottom', title: '查看详情' do %>
        <i class='icon-user'></i>
      <% end %>
      <% if !current_user?(user) && current_user.admin? %>
        <a class='btn btn-success btn-mini has-tooltip' data-placement='bottom' title='修改权限' data-toggle='modal' href='#modal-form' role='button'>
          <i class='icon-edit'></i>
        </a>
        <div class='modal hide fade text-left' id='modal-form' role='dialog' tabindex='-1'>
          <div class='modal-header'>
            <button class='close' data-dismiss='modal' type='button'>&times;</button>
            <h3>用户权限设置</h3>
          </div>
          <div class='modal-body'>
            <%= form_for(user) do |f| %>
              <div class='controls-group'>
                <%= f.label :role_cname, "角色", class: "control-label" %>
                <div class='controls'>
                  <%= f.select :role_id, Role.all.collect {|r| [r.role_cname, r.id] }, {:include_blank => true}, class: "span12" %>
                </div>
              </div>
            <% end %>
          </div>
          <div class='modal-footer'>
            <button class='btn' data-dismiss='modal'>关闭</button>
            <%= button_tag class: 'btn btn-primary' do %>
              修改
            <% end %>
          </div>
        </div>
        <a class='btn btn-primary btn-mini has-tooltip' data-placement='bottom' title='重置密码' href='#'>
          <i class='icon-refresh'></i>
        </a>
        <%= link_to user_path(user.id), method: :delete, class: 'btn btn-danger btn-mini has-tooltip', :'data-placement'=>'bottom', title: '删除', data: {confirm: "确认删除？"}  do %>
          <i class='icon-remove'></i>
        <% end %>
      <% end %>
    <div>
  </td>
</tr>

app/views/users/edit.html.erb
<% provide(:title, "编辑") %>
<div class='page-header'>
  <h1 class='pull-left'>
    <i class='icon-wrench'></i>
    <span>编辑</span>
  </h1>
</div>
<div class='row-fluid'>
  <div class='span3 box'>
    <div class='box-content'>
      <%= image_tag "default_user.gif", alt: "default_user.gif", size:"230x230" %>
    </div>
  </div>
  <div class='span9 box'>
    <div class='box-content box-double-padding'>
    	<%= form_for(@user) do |f| %>
        <fieldset>
          <div class='span4'>
          	<%= render 'shared/error_messages', object: f.object %>
            <div class='lead'>
              <i class='icon-signin text-contrast'></i>
              登录信息
            </div>
            <small class='muted'>您登录时所需要的信息，用户名、邮箱地址、密码信息</small>
          </div>
          <div class='span7 offset1'>
            <div class='control-group'>
              <%= f.label :ename, "英文名", class: "control-label" %>
              <div class='controls'>
              	<%= f.text_field :ename, class: "span12", placeholder: "英文名" %>
              </div>
            </div>
            <div class='control-group'>
              <%= f.label :email, "邮箱地址", class: "control-label" %>
              <div class='controls'>
              	<%= f.text_field :email, class: "span12", placeholder: "邮箱地址" %>
              </div>
            </div>
            <hr class='hr-normal' />
            <div class='control-group'>
              <div class='controls'>
                <label class='checkbox'>
                  <%= check_box_tag :_checked, "1", false, {:'data-target'=>'#change-password', :'data-toggle'=>'collapse'} %>
                  修改密码？
                </label>
              </div>
            </div>
            <div class='collapse' id='change-password'>
              <div class='control-group'>
                <%= f.label :password, "密码", class: "control-label" %>
                <div class='controls'>
                	<%= f.password_field :password, class: 'span12', placeholder: '密码' %>
                </div>
              </div>
              <div class='control-group'>
                <%= f.label :password_confirmation, "确认密码", class: "control-label" %>
                <div class='controls'>
                  <%= f.password_field :password_confirmation, class: 'span12', placeholder: '确认密码' %>
                </div>
              </div>
            </div>
          </div>
        </fieldset>
        <hr class='hr-normal' />
        <fieldset>
          <div class='span4 box'>
            <div class='lead'>
              <i class='icon-user text-contrast'></i>
              附加信息
            </div>
            <small class='muted'>附加信息，只做备注</small>
          </div>
        	<div class='span7 offset1'>
            <div class='control-group'>
              <%= f.label :cname, "中文名", class: "control-label" %>
              <div class='controls'>
                <%= f.text_field :cname, class: "span12", placeholder: "中文名" %>
              </div>
            </div>
            <div class='control-group'>
              <%= f.label :branch_code, "所属分支机构", class: "control-label" %>
              <div class='controls'>
                <%= f.select :branch_id, Branch.all.collect { |b| [b.branch_name, b.id] },{:include_blank => true}, class: "span12" %>
              </div>
            </div>
          </div>
        </fieldset>
        <div class='form-actions' style='margin-bottom: 0;'>
          <div class='text-right'>
            <%= button_tag class: "btn btn-primary btn-large" do %>
            	<i class='icon-save'></i>
            	保存修改
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '所有用户') %>
<div class='page-header'>
  <h1 class='pull-left'>
    <i class='icon-list'></i>
    <span>用户列表</span>
  </h1>
</div>
<div class='row-fluid'>
  <div class='span12 box bordered-box orange-border' style='margin-bottom:0;'>
    <div class='box-header purple-background'>
      <div class='title'>用户信息表</div>
      <div class='actions'>
        <a href="#" class="btn box-remove btn-mini btn-link"><i class='icon-remove'></i>
        </a>
        <a href="#" class="btn box-collapse btn-mini btn-link"><i></i>
        </a>
      </div>
    </div>
    <div class='box-content box-no-padding'>
      <div class='responsive-table'>
        <div class='scrollable-area'>
          <table class='data-table-column-filter table table-bordered table-striped table-hover' style='margin-bottom:0;'>
            <thead>
              <tr>
                <th>
                  用户名
                </th>
                <th>
                  邮箱地址
                </th>
                <th>
                  所属分支机构
                </th>
                <th>
                  角色
                </th>
                <th>
                  创建时间
                </th>
                <th>
                  操作
                </th>
              </tr>
            </thead>
            <tbody>
              <%= render @users %>
            </tbody>
            <tfoot>
              <tr>
                <th>用户名</th>
                <th>邮箱地址</th>
                <th>所属分支机构</th>
                <th>角色</th>
                <th colspan='2'>创建时间</th>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class='controls'>
  <div class='caret'></div>
  <div class='form-wrapper'>
    <h1 class='text-center'>新用户注册</h1>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class='row-fluid'>
        <div class='span12 icon-over-input'>
          <%= f.text_field :ename, class: "span12", placeholder: "英文名" %>
          <i class='icon-user muted'></i>
        </div>
      </div>
      <div class='row-fluid'>
        <div class='span12 icon-over-input'>
          <%= f.text_field :cname, class: "span12", placeholder: "中文名" %>
          <i class='icon-user muted'></i>
        </div>
      </div>
      <div class='row-fluid'>
        <div class='span12 icon-over-input'>
          <%= f.text_field :email, class: "span12", placeholder: "邮箱地址" %>
          <i class='icon-user muted'></i>
        </div>
      </div>
      <div class='row-fluid'>
        <div class='span12 icon-over-input'>
          <%= f.select :branch_id, Branch.all.collect { |b| [b.branch_name, b.id] }, {:include_blank => true}, class: "span12" %>
        </div>
      </div>
      <div class='row-fluid'>
        <div class='span12 icon-over-input'>
          <%= f.password_field :password, class: "span12", placeholder: "密码" %>
          <i class='icon-lock muted'></i>
        </div>
      </div>
      <div class='row-fluid'>
        <div class='span12 icon-over-input'>
          <%= f.password_field :password_confirmation, class: "span12", placeholder: "确认密码" %>
          <i class='icon-lock muted'></i>
        </div>
      </div>
      <%= f.submit "注册", class: "btn btn-block" %>
    <% end %>
    <div class='text-center'>
      <hr class='hr-normal' />
      <%= link_to root_path do %>
        <i class='icon-chevron-left'></i>
        返回登录
      <% end %>
    </div>
  </div>
</div>
<div class='login-action text-center'>
  <%= link_to '#' do %>
    <i class='icon-lock'></i>
    忘记密码？
  <% end %>
</div>

app/views/users/password.html.erb
<% provide(:title, '修改密码') %>
<div class='page-header'>
  <h1 class='pull-left'>
    <i class='icon-cog'></i>
    <span>修改密码</span>
  </h1>
</div>
<div class='row-fluid'>
  <div class='box'>
    <div class='box-content'>
      <%= form_for @user, :url => url_for(:controller => 'users', :action => "change_password"), 
            :html => {class:'form-horizontal'} do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class='control-group'>
          <%= f.label :current_password, "旧密码", class: "control-label" %>
          <div class='controls'>
            <%= f.password_field :current_password, placeholder: '旧密码' %>
          </div>
        </div>
        <div class='control-group'>
          <%= f.label :password, "新密码", class: "control-label" %>
          <div class='controls'>
            <%= f.password_field :password, placeholder: '新密码' %>
          </div>
        </div>
        <div class='control-group'>
          <%= f.label :password_confirmation, "确认密码", class: "control-label" %>
          <div class='controls'>
            <%= f.password_field :password_confirmation, placeholder: '确认密码' %>
          </div>
        </div>
        <div class='form-actions'>
          <div class='text-left'>
            <%= button_tag class: "btn btn-primary btn-large" do %>
              <i class='icon-save'></i>
              保存
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.cname) %>
<div class='page-header'>
  <h1 class='pull-left'>
    <i class='icon-user'></i>
    <span>查看</span>
  </h1>
</div>
<div class='row-fluid'>
  <div class='span3 box'>
    <div class='box-content'>
      <%= image_tag "default_user.gif", alt: "default_user.gif", size:"230x230" %>
    </div>
  </div>
  <div class='span9 box'>
    <div class='box-content box-double-padding'>
      <fieldset>
        <div class='span4'>
          <div class='lead'>
            <i class='icon-signin text-contrast'></i>
            登录信息
          </div>
          <small class='muted'>您登录时所需要的信息，用户名、邮箱地址、密码信息</small>
        </div>
        <div class='span7 offset1'>
          <div class='control-group'>
            <%= label :user, :ename, "英文名", class: "control-label" %>
            <div class='controls'>
              <%= text_field :user, :ename, class: "span12", readonly: true %>
            </div>
          </div>
          <div class='control-group'>
            <%= label :user, :email, "邮箱地址", class: "control-label" %>
            <div class='controls'>
              <%= text_field :user, :email, class: "span12", readonly: true %>
            </div>
          </div>
        </div>
      </fieldset>
      <hr class='hr-normal' />
      <fieldset>
        <div class='span4 box'>
          <div class='lead'>
            <i class='icon-user text-contrast'></i>
            附加信息
          </div>
          <small class='muted'>附加信息，只做备注</small>
        </div>
        <div class='span7 offset1'>
          <div class='control-group'>
            <%= label :user, :cname, "中文名", class: "control-label" %>
            <div class='controls'>
              <%= text_field :user, :cname, class: "span12", readonly: true %>
            </div>
          </div>
          <div class='control-group'>
          <%= label :user, :branch_id, "所属分支机构", class: "control-label" %>
            <div class='controls'>
              <%= text_field :user, :branch_id, value: @user.branch.branch_name, class: "span12", readonly:true %>
            </div>
          </div>
          <div class='control-group'>
            <%= label :user, :role_id, "角色", class: "control-label" %>
            <div class='controls'>
              <%= text_field :user, :role_id, value: @user.role.role_cname, class: "span12", readonly:true %>
            </div>
          </div>
          <div class='control-group'>
            <%= label :user, :created_at, "创建时间", class: "control-label" %>
            <div class='controls'>
              <%= text_field :user, :created_at, class: "span12", readonly:true, value: @user.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
            </div>
          </div>
        </div>
      </fieldset>
    </div>
  </div>
</div>